// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: card/card.proto

package cardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	CardBrand     string                 `protobuf:"bytes,4,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateCardRequest) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateCardRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CreateCardRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCardsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsByAccountRequest) Reset() {
	*x = ListCardsByAccountRequest{}
	mi := &file_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsByAccountRequest) ProtoMessage() {}

func (x *ListCardsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListCardsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *ListCardsByAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type ListCardsByClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsByClientRequest) Reset() {
	*x = ListCardsByClientRequest{}
	mi := &file_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsByClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsByClientRequest) ProtoMessage() {}

func (x *ListCardsByClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsByClientRequest.ProtoReflect.Descriptor instead.
func (*ListCardsByClientRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *ListCardsByClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardResponse        `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_card_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *ListCardsResponse) GetCards() []*CardResponse {
	if x != nil {
		return x.Cards
	}
	return nil
}

type BlockCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCardRequest) Reset() {
	*x = BlockCardRequest{}
	mi := &file_card_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCardRequest) ProtoMessage() {}

func (x *BlockCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCardRequest.ProtoReflect.Descriptor instead.
func (*BlockCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{5}
}

func (x *BlockCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnblockCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockCardRequest) Reset() {
	*x = UnblockCardRequest{}
	mi := &file_card_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockCardRequest) ProtoMessage() {}

func (x *UnblockCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockCardRequest.ProtoReflect.Descriptor instead.
func (*UnblockCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *UnblockCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeactivateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateCardRequest) Reset() {
	*x = DeactivateCardRequest{}
	mi := &file_card_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateCardRequest) ProtoMessage() {}

func (x *DeactivateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateCardRequest.ProtoReflect.Descriptor instead.
func (*DeactivateCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *DeactivateCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber     string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardNumberFull string                 `protobuf:"bytes,3,opt,name=card_number_full,json=cardNumberFull,proto3" json:"card_number_full,omitempty"`
	CardType       string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardName       string                 `protobuf:"bytes,5,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	CardBrand      string                 `protobuf:"bytes,6,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AccountNumber  string                 `protobuf:"bytes,9,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Cvv            string                 `protobuf:"bytes,10,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardLimit      string                 `protobuf:"bytes,11,opt,name=card_limit,json=cardLimit,proto3" json:"card_limit,omitempty"`
	Status         string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	OwnerType      string                 `protobuf:"bytes,13,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId        uint64                 `protobuf:"varint,14,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_card_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{8}
}

func (x *CardResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardResponse) GetCardNumberFull() string {
	if x != nil {
		return x.CardNumberFull
	}
	return ""
}

func (x *CardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardResponse) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *CardResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *CardResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CardResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CardResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CardResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardResponse) GetCardLimit() string {
	if x != nil {
		return x.CardLimit
	}
	return ""
}

func (x *CardResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CardResponse) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CardResponse) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type CreateAuthorizedPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	AccountId     uint64                 `protobuf:"varint,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorizedPersonRequest) Reset() {
	*x = CreateAuthorizedPersonRequest{}
	mi := &file_card_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorizedPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorizedPersonRequest) ProtoMessage() {}

func (x *CreateAuthorizedPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorizedPersonRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorizedPersonRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAuthorizedPersonRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *CreateAuthorizedPersonRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAuthorizedPersonRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetAuthorizedPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizedPersonRequest) Reset() {
	*x = GetAuthorizedPersonRequest{}
	mi := &file_card_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizedPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizedPersonRequest) ProtoMessage() {}

func (x *GetAuthorizedPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizedPersonRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizedPersonRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{10}
}

func (x *GetAuthorizedPersonRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthorizedPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	AccountId     uint64                 `protobuf:"varint,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedPersonResponse) Reset() {
	*x = AuthorizedPersonResponse{}
	mi := &file_card_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPersonResponse) ProtoMessage() {}

func (x *AuthorizedPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPersonResponse.ProtoReflect.Descriptor instead.
func (*AuthorizedPersonResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{11}
}

func (x *AuthorizedPersonResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthorizedPersonResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *AuthorizedPersonResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AuthorizedPersonResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AuthorizedPersonResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateVirtualCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CardBrand     string                 `protobuf:"bytes,3,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	UsageType     string                 `protobuf:"bytes,4,opt,name=usage_type,json=usageType,proto3" json:"usage_type,omitempty"`
	MaxUses       int32                  `protobuf:"varint,5,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	ExpiryMonths  int32                  `protobuf:"varint,6,opt,name=expiry_months,json=expiryMonths,proto3" json:"expiry_months,omitempty"`
	CardLimit     string                 `protobuf:"bytes,7,opt,name=card_limit,json=cardLimit,proto3" json:"card_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVirtualCardRequest) Reset() {
	*x = CreateVirtualCardRequest{}
	mi := &file_card_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVirtualCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVirtualCardRequest) ProtoMessage() {}

func (x *CreateVirtualCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVirtualCardRequest.ProtoReflect.Descriptor instead.
func (*CreateVirtualCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{12}
}

func (x *CreateVirtualCardRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateVirtualCardRequest) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateVirtualCardRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *CreateVirtualCardRequest) GetUsageType() string {
	if x != nil {
		return x.UsageType
	}
	return ""
}

func (x *CreateVirtualCardRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreateVirtualCardRequest) GetExpiryMonths() int32 {
	if x != nil {
		return x.ExpiryMonths
	}
	return 0
}

func (x *CreateVirtualCardRequest) GetCardLimit() string {
	if x != nil {
		return x.CardLimit
	}
	return ""
}

type SetCardPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCardPinRequest) Reset() {
	*x = SetCardPinRequest{}
	mi := &file_card_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCardPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCardPinRequest) ProtoMessage() {}

func (x *SetCardPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCardPinRequest.ProtoReflect.Descriptor instead.
func (*SetCardPinRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{13}
}

func (x *SetCardPinRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetCardPinRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type SetCardPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCardPinResponse) Reset() {
	*x = SetCardPinResponse{}
	mi := &file_card_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCardPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCardPinResponse) ProtoMessage() {}

func (x *SetCardPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCardPinResponse.ProtoReflect.Descriptor instead.
func (*SetCardPinResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{14}
}

func (x *SetCardPinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCardPinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyCardPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCardPinRequest) Reset() {
	*x = VerifyCardPinRequest{}
	mi := &file_card_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCardPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCardPinRequest) ProtoMessage() {}

func (x *VerifyCardPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCardPinRequest.ProtoReflect.Descriptor instead.
func (*VerifyCardPinRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyCardPinRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VerifyCardPinRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type VerifyCardPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCardPinResponse) Reset() {
	*x = VerifyCardPinResponse{}
	mi := &file_card_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCardPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCardPinResponse) ProtoMessage() {}

func (x *VerifyCardPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCardPinResponse.ProtoReflect.Descriptor instead.
func (*VerifyCardPinResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyCardPinResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyCardPinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TemporaryBlockCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DurationHours int32                  `protobuf:"varint,2,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporaryBlockCardRequest) Reset() {
	*x = TemporaryBlockCardRequest{}
	mi := &file_card_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporaryBlockCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryBlockCardRequest) ProtoMessage() {}

func (x *TemporaryBlockCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryBlockCardRequest.ProtoReflect.Descriptor instead.
func (*TemporaryBlockCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{17}
}

func (x *TemporaryBlockCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TemporaryBlockCardRequest) GetDurationHours() int32 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

func (x *TemporaryBlockCardRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UseCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCardRequest) Reset() {
	*x = UseCardRequest{}
	mi := &file_card_card_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCardRequest) ProtoMessage() {}

func (x *UseCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCardRequest.ProtoReflect.Descriptor instead.
func (*UseCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{18}
}

func (x *UseCardRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UseCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCardResponse) Reset() {
	*x = UseCardResponse{}
	mi := &file_card_card_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCardResponse) ProtoMessage() {}

func (x *UseCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCardResponse.ProtoReflect.Descriptor instead.
func (*UseCardResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{19}
}

func (x *UseCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_card_card_proto protoreflect.FileDescriptor

const file_card_card_proto_rawDesc = "" +
	"\n" +
	"\x0fcard/card.proto\x12\x04card\"\x93\x01\n" +
	"\x11CreateCardRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x04 \x01(\tR\tcardBrand\" \n" +
	"\x0eGetCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"B\n" +
	"\x19ListCardsByAccountRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"7\n" +
	"\x18ListCardsByClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"=\n" +
	"\x11ListCardsResponse\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.card.CardResponseR\x05cards\"\"\n" +
	"\x10BlockCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"$\n" +
	"\x12UnblockCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"'\n" +
	"\x15DeactivateCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xaa\x03\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12(\n" +
	"\x10card_number_full\x18\x03 \x01(\tR\x0ecardNumberFull\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1b\n" +
	"\tcard_name\x18\x05 \x01(\tR\bcardName\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x06 \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12%\n" +
	"\x0eaccount_number\x18\t \x01(\tR\raccountNumber\x12\x10\n" +
	"\x03cvv\x18\n" +
	" \x01(\tR\x03cvv\x12\x1d\n" +
	"\n" +
	"card_limit\x18\v \x01(\tR\tcardLimit\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"owner_type\x18\r \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x0e \x01(\x04R\aownerId\"\xfc\x01\n" +
	"\x1dCreateAuthorizedPersonRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"account_id\x18\b \x01(\x04R\taccountId\",\n" +
	"\x1aGetAuthorizedPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa6\x02\n" +
	"\x18AuthorizedPersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\x04R\taccountId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xf9\x01\n" +
	"\x18CreateVirtualCardRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x03 \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"usage_type\x18\x04 \x01(\tR\tusageType\x12\x19\n" +
	"\bmax_uses\x18\x05 \x01(\x05R\amaxUses\x12#\n" +
	"\rexpiry_months\x18\x06 \x01(\x05R\fexpiryMonths\x12\x1d\n" +
	"\n" +
	"card_limit\x18\a \x01(\tR\tcardLimit\"5\n" +
	"\x11SetCardPinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"H\n" +
	"\x12SetCardPinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x14VerifyCardPinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"G\n" +
	"\x15VerifyCardPinResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x19TemporaryBlockCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0eduration_hours\x18\x02 \x01(\x05R\rdurationHours\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\" \n" +
	"\x0eUseCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"+\n" +
	"\x0fUseCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8c\x05\n" +
	"\vCardService\x129\n" +
	"\n" +
	"CreateCard\x12\x17.card.CreateCardRequest\x1a\x12.card.CardResponse\x123\n" +
	"\aGetCard\x12\x14.card.GetCardRequest\x1a\x12.card.CardResponse\x12N\n" +
	"\x12ListCardsByAccount\x12\x1f.card.ListCardsByAccountRequest\x1a\x17.card.ListCardsResponse\x12L\n" +
	"\x11ListCardsByClient\x12\x1e.card.ListCardsByClientRequest\x1a\x17.card.ListCardsResponse\x127\n" +
	"\tBlockCard\x12\x16.card.BlockCardRequest\x1a\x12.card.CardResponse\x12;\n" +
	"\vUnblockCard\x12\x18.card.UnblockCardRequest\x1a\x12.card.CardResponse\x12A\n" +
	"\x0eDeactivateCard\x12\x1b.card.DeactivateCardRequest\x1a\x12.card.CardResponse\x12]\n" +
	"\x16CreateAuthorizedPerson\x12#.card.CreateAuthorizedPersonRequest\x1a\x1e.card.AuthorizedPersonResponse\x12W\n" +
	"\x13GetAuthorizedPerson\x12 .card.GetAuthorizedPersonRequest\x1a\x1e.card.AuthorizedPersonResponse2\xeb\x02\n" +
	"\x12VirtualCardService\x12G\n" +
	"\x11CreateVirtualCard\x12\x1e.card.CreateVirtualCardRequest\x1a\x12.card.CardResponse\x12?\n" +
	"\n" +
	"SetCardPin\x12\x17.card.SetCardPinRequest\x1a\x18.card.SetCardPinResponse\x12H\n" +
	"\rVerifyCardPin\x12\x1a.card.VerifyCardPinRequest\x1a\x1b.card.VerifyCardPinResponse\x12I\n" +
	"\x12TemporaryBlockCard\x12\x1f.card.TemporaryBlockCardRequest\x1a\x12.card.CardResponse\x126\n" +
	"\aUseCard\x12\x14.card.UseCardRequest\x1a\x15.card.UseCardResponseB+Z)github.com/exbanka/contract/cardpb;cardpbb\x06proto3"

var (
	file_card_card_proto_rawDescOnce sync.Once
	file_card_card_proto_rawDescData []byte
)

func file_card_card_proto_rawDescGZIP() []byte {
	file_card_card_proto_rawDescOnce.Do(func() {
		file_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_card_proto_rawDesc), len(file_card_card_proto_rawDesc)))
	})
	return file_card_card_proto_rawDescData
}

var file_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_card_card_proto_goTypes = []any{
	(*CreateCardRequest)(nil),             // 0: card.CreateCardRequest
	(*GetCardRequest)(nil),                // 1: card.GetCardRequest
	(*ListCardsByAccountRequest)(nil),     // 2: card.ListCardsByAccountRequest
	(*ListCardsByClientRequest)(nil),      // 3: card.ListCardsByClientRequest
	(*ListCardsResponse)(nil),             // 4: card.ListCardsResponse
	(*BlockCardRequest)(nil),              // 5: card.BlockCardRequest
	(*UnblockCardRequest)(nil),            // 6: card.UnblockCardRequest
	(*DeactivateCardRequest)(nil),         // 7: card.DeactivateCardRequest
	(*CardResponse)(nil),                  // 8: card.CardResponse
	(*CreateAuthorizedPersonRequest)(nil), // 9: card.CreateAuthorizedPersonRequest
	(*GetAuthorizedPersonRequest)(nil),    // 10: card.GetAuthorizedPersonRequest
	(*AuthorizedPersonResponse)(nil),      // 11: card.AuthorizedPersonResponse
	(*CreateVirtualCardRequest)(nil),      // 12: card.CreateVirtualCardRequest
	(*SetCardPinRequest)(nil),             // 13: card.SetCardPinRequest
	(*SetCardPinResponse)(nil),            // 14: card.SetCardPinResponse
	(*VerifyCardPinRequest)(nil),          // 15: card.VerifyCardPinRequest
	(*VerifyCardPinResponse)(nil),         // 16: card.VerifyCardPinResponse
	(*TemporaryBlockCardRequest)(nil),     // 17: card.TemporaryBlockCardRequest
	(*UseCardRequest)(nil),                // 18: card.UseCardRequest
	(*UseCardResponse)(nil),               // 19: card.UseCardResponse
}
var file_card_card_proto_depIdxs = []int32{
	8,  // 0: card.ListCardsResponse.cards:type_name -> card.CardResponse
	0,  // 1: card.CardService.CreateCard:input_type -> card.CreateCardRequest
	1,  // 2: card.CardService.GetCard:input_type -> card.GetCardRequest
	2,  // 3: card.CardService.ListCardsByAccount:input_type -> card.ListCardsByAccountRequest
	3,  // 4: card.CardService.ListCardsByClient:input_type -> card.ListCardsByClientRequest
	5,  // 5: card.CardService.BlockCard:input_type -> card.BlockCardRequest
	6,  // 6: card.CardService.UnblockCard:input_type -> card.UnblockCardRequest
	7,  // 7: card.CardService.DeactivateCard:input_type -> card.DeactivateCardRequest
	9,  // 8: card.CardService.CreateAuthorizedPerson:input_type -> card.CreateAuthorizedPersonRequest
	10, // 9: card.CardService.GetAuthorizedPerson:input_type -> card.GetAuthorizedPersonRequest
	12, // 10: card.VirtualCardService.CreateVirtualCard:input_type -> card.CreateVirtualCardRequest
	13, // 11: card.VirtualCardService.SetCardPin:input_type -> card.SetCardPinRequest
	15, // 12: card.VirtualCardService.VerifyCardPin:input_type -> card.VerifyCardPinRequest
	17, // 13: card.VirtualCardService.TemporaryBlockCard:input_type -> card.TemporaryBlockCardRequest
	18, // 14: card.VirtualCardService.UseCard:input_type -> card.UseCardRequest
	8,  // 15: card.CardService.CreateCard:output_type -> card.CardResponse
	8,  // 16: card.CardService.GetCard:output_type -> card.CardResponse
	4,  // 17: card.CardService.ListCardsByAccount:output_type -> card.ListCardsResponse
	4,  // 18: card.CardService.ListCardsByClient:output_type -> card.ListCardsResponse
	8,  // 19: card.CardService.BlockCard:output_type -> card.CardResponse
	8,  // 20: card.CardService.UnblockCard:output_type -> card.CardResponse
	8,  // 21: card.CardService.DeactivateCard:output_type -> card.CardResponse
	11, // 22: card.CardService.CreateAuthorizedPerson:output_type -> card.AuthorizedPersonResponse
	11, // 23: card.CardService.GetAuthorizedPerson:output_type -> card.AuthorizedPersonResponse
	8,  // 24: card.VirtualCardService.CreateVirtualCard:output_type -> card.CardResponse
	14, // 25: card.VirtualCardService.SetCardPin:output_type -> card.SetCardPinResponse
	16, // 26: card.VirtualCardService.VerifyCardPin:output_type -> card.VerifyCardPinResponse
	8,  // 27: card.VirtualCardService.TemporaryBlockCard:output_type -> card.CardResponse
	19, // 28: card.VirtualCardService.UseCard:output_type -> card.UseCardResponse
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_card_card_proto_init() }
func file_card_card_proto_init() {
	if File_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_card_proto_rawDesc), len(file_card_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_card_card_proto_goTypes,
		DependencyIndexes: file_card_card_proto_depIdxs,
		MessageInfos:      file_card_card_proto_msgTypes,
	}.Build()
	File_card_card_proto = out.File
	file_card_card_proto_goTypes = nil
	file_card_card_proto_depIdxs = nil
}
